apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: raven 
  name: raven 
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: raven 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: raven 
      name: raven 
    spec:
      containers:
      - env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: secretwithmyvaulttoken 
        - name: REPO_URL
          value: ssh://git@example.com
        - name: SECRET_ENGINE
          value: mykv 
        - name: DEST_ENV
          value: myenv 
        - name: CLONE_PATH
          value: /tmp/clone
          image: ghcr.io/volck/raven:v1.0.0 
        imagePullPolicy: IfNotPresent
        name: raven 
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secret/ssc
          name: ssc
        - mountPath: /secret
          name: sshprivatekey
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sshprivatekey
        secret:
          defaultMode: 420
          items:
          - key: ssh-privatekey
            path: sshKey
          secretName: mysecretwiththesshprivatekey 
      - name: ssc
        secret:
          defaultMode: 420
          secretName: sealedsecretcertificatesecret 
  triggers:
  - type: ConfigChange
